#!/bin/bash
uname -a
echo "Julia+CMSSW wrapper"

julia -E "versioninfo()"

#use system python
PYPATH=$(dirname `which python`)

#get the absolute path of this script
scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#set the CMSSW path
source $scriptdir/setenv.sh && PATH=$PYPATH:$PATH $LOCAL_JULIA_DIR/usr/bin/julia-readline -F $@
