#!/bin/bash
uname -a
echo "Julia+CMSSW wrapper"

julia -E "versioninfo()"

#get the absolute path of this script
scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#set the CMSSW path and run Julia
source $scriptdir/setenv.sh && $LOCAL_JULIA_DIR/usr/bin/julia-basic -F $@
